question_data = [
                     {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
                      "question": "This is the correct spelling of &quot;Supercalifragilisticexpialidocious&quot;.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                      "question": "The word &quot;news&quot; originates from the first letters of the 4 main directions on a compass (North, East, West, South).",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                      "question": "The color orange is named after the fruit.", "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                      "question": "On average, at least 1 person is killed by a drunk driver in the United States every hour.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                      "question": "Kissing someone for one minute burns about 2 calories.", "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
                      "question": "In Scandinavian languages, the letter &Aring; means river.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
                      "question": "Spoon theory is a theory, utilizing &quot;Spoons&quot; as a metaphor for energy they can use in a day.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                      "question": "A pasodoble is a type of Italian pasta sauce.", "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                      "question": "Slovakia is a member of European Union-", "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                      "question": "Instant mashed potatoes were invented by Canadian Edward Asselbergs in 1962.",
                      "correct_answer": "True", "incorrect_answers": ["False"]}]
